### ISSUE TITLE
Bower package only includes demo/

### ISSUE THREAD

**Issue by bencoveney** [milligram/milligram-sass#4]
I have installed the bower package however it only seems to contain the demo/ directory and none of the .sass code.

I can see that the src/ directory is excluded in the bower.json config file but can't see any mention of the dist/ directory so I am not sure why exactly it is not being installed.

![2016-02-08 08_33_02-](https://cloud.githubusercontent.com/assets/1053494/12881075/a10d5210-ce3e-11e5-9257-c43ba4447c2b.png)

**Comment by bencoveney** [comment]
Fixed using the instructions here - https://github.com/milligram/milligram-scss/issues/4

**Comment by cjpatoilo** [comment]
@bencoveney sorry guy!!!

I've been out for a long time. I am updating all repositories during these days and everything will return to normal.
